font_family JetbrainsMono Nerd Font Mono
font_size   12 

disable_ligatures always
enable_audio_bell no

shell             zsh
shell_integration disabled

url_style curly

remember_window_size  yes
window_padding_width  5
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.1 0.3


background_opacity            0.80
scrollbar_handle_opacity      0.2
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0.1
confirm_os_window_close       0

sync_to_monitor no

# Color Themes (OceanicMaterial)
background #1c262b
foreground #c1c8d6
cursor #b2b8c3
selection_background #6dc1b8
color0 #000000
color8 #767676
color1 #ee2a29
color9 #dc5b60
color2 #3fa33f
color10 #70be71
color3 #fee92e
color11 #fef063
color4 #1d80ef
color12 #53a4f3
color5 #8800a0
color13 #a94dbb
color6 #16aec9
color14 #42c6d9
color7 #a4a4a4
color15 #fffefe
selection_foreground #1c262b
