STATE="cat /sys/class/power_supply/ACAD/online"
BAT="cat /sys/class/power_supply/BAT1/capacity"

general {
    lock_cmd = pidof hyprlock || hyprlock       # Prevents hyprlock multi service
    before_sleep_cmd = loginctl lock-session    # Lock screen before suspend 
    after_sleep_cmd = hyprctl dispatch dpms on || hyprctl dispatch 'hl.dsp.global({"quickshell:lockFocus"})' || hyprctl dispath 'hl.dsp.dpms({ action="enable" })'  # Auto turn on monitor at resume
}

listener { # auto shutdown when battery under 5% and not charging with low timeout
    timeout = 10
    on-timeout = sh -c '[[ "$( cat /sys/class/power_supply/ACAD/online | head -n1 )" -eq 0 && "$( cat /sys/class/power_supply/BAT*/capacity)" -le 5 ]] && $HOME/.config/wlogout/logout.lua && systemctl poweroff'
}

listener { # charging shut off screen
    timeout = 560
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener { # battery lock session
    timeout = 200
    on-timeout = sh -c '[ "$( cat /sys/class/power_supply/ACAD/online | head -n1 )" -eq 0 ] && loginctl lock-session && sudo ryzenadj --power-saving && hyprctl dispatch "hl.dsp.dpms({action=disable})"'
    on-resume = 'sudo-ryzenadj --max-performance ' # && hyprctl dispatch "hl.dsp.dpms({action=enable})"'
}

listener { # charging lock session
    timeout = 500
    on-timeout = sh -c '[ "$( cat /sys/class/power_supply/ACAD/online | head -n1 )" -eq 1 ] && loginctl lock-session && sudo ryzenadj --power-saving && hyprctl dispatch "hl.dsp.dpms({action=disable})"'
    on-resume = 'sudo ryzenadj --max-performance && hyprctl dispatch "hl.dsp.dpms({action=enable})"'
}

listener { # battery sleep
    timeout = 550
    on-timeout = sh -c '[ "$( cat /sys/class/power_supply/ACAD/online | head -n1 )" -eq 0 ] && systemctl suspend'
}

listener { # charging sleep, doesn't require plug check as it triggers at longest timeout, triggers battery sleep first before even touch this timeout in battery
    timeout = 1800
    on-timeout = systemctl suspend
}
